[workspace]
members = [
    "cflib",
    "core",
    "plugins/test_plugin",
    "plugins/fs_store",
    "plugins/random_select",
    "plugins/basic_mutate",
    "plugins/basic_run",
    "plugins/save_result",
    "cf_tui",
]