[workspace]
members = [
    "cflib",
    "core",
    "plugins/test_plugin",
    "plugins/fs_store",
    "plugins/select_input",
    "plugins/basic_mutate",
    "plugins/run_target",
    "plugins/save_result",
    "cf_tui",
]