[package]
name = "cflib"
version = "0.0.1"
authors = ["Elast0ny <Elast0ny00@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "cflib"

[dependencies]
log = "0.*"
simple_parse = {version = "*", path = "../../simple_parse"}

[build-dependencies]
rustc_version = "*"